sudo: required
services:
  - docker

before_install:
  - docker build -t tabriz/docker-react-frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true tabriz/docker-react-frontend npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "DockerReactFrontend-env"
  bucket_name: "elasticbeanstalk-us-east-2-123456789012"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"